-   id: gendocs
    name: Generate Documentation
    entry: python -m kyanit_buildtools.gendocs
    pass_filenames: False
    require_serial: True
    language: python

-   id: genrelease
    name: Release and Changelog Generation
    entry: python -m kyanit_buildtools.genrelease
    pass_filenames: False
    require_serial: True
    language: python
